### PR TITLE
 Added German language

### PR DESCRIPTION
**Pull request by jo-shi**

### CODE REVIEW

**Comment by erichgoldman** [comment]
Thank you! Machine translation looks good. I will test the integration in my test environment and then merge. It will then be included in the next official release through Mozilla.

**Comment by erichgoldman** [comment]
Thanks, it seems to be working. Also tested de-AT and de-CH and confirmed it will load to de-*

Screenshot showing German working

**Comment by erichgoldman** [comment]
I am going to add you into the manifest, which is created through: https://github.com/erichgoldman/add-url-to-window-title/blob/master/package.json

There is a field in for `translators` in [package.json](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#Key_reference). Would you like me to list your full name or just your github handle?

**Comment by jo-shi** [comment]
Put the full name into in package.json. I have made some experinces with the plugin and will write a german guidance for a successful usage.

**Comment by erichgoldman** [comment]
Updated package.json --> https://github.com/erichgoldman/add-url-to-window-title/blob/master/package.json#L7

Thank you for the additional write up, I appreciate your support and help in spreading my add on to more people! Hope it is useful and helpful, let me know of any further issues or bugs.

**Pull request merged**
